name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make RUSTCSRC
      run: make RUSTCSRC
    - name: make
      run: make all && make -C tools/minicargo
    - name: make test
      run: make test
